enum DataConstants {
    GETDATA_SUCCESS = 'GETDATA_SUCCESS',
    CREATEDATA_SUCCESS = 'CREATEDATA_SUCCESS',

    GETDATA_REQUEST = 'GETDATA_REQUEST',
    CREATEDATA_REQUEST = 'CREATEDATA_REQUEST',

    GETDATA_FAILURE = 'GETDATA_FAILURE',
    CREATEDATA_FAILURE = 'CREATEDATA_FAILURE',

    SORTDATA = 'SORTDATA'
};

export default DataConstants;