enum UserConstants {
    REGISTER_REQUEST = 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS = 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE = 'USERS_REGISTER_FAILURE',

    GETRECIPIENT_REQUEST = 'GETRECIPIENT_REQUEST',
    GETRECIPIENT_SUCCESS = 'GETRECIPIENT_SUCCESS',
    GETRECIPIENT_FAILURE = 'GETRECIPIENT_FAILURE',
};

export default UserConstants;